### ISSUE TITLE
Imposible to create gui

### ISSUE THREAD

**Issue by zimavi** [knector01/gui.lua#1]
I wrote a gui, just to try if I can create an installer. But every time I got an error `gui.lua:291: attempt to index local 'child' (a nil value)`
I can not fix this, because I am not so good at lua. But your code `demo.lua` works. Help, please.
Here is the code:
```lua
local gui = require('gui')

local root = gui.Root:new()

local box = gui.LinearContainer:new(root,2,1,1)
--local box2 = gui.LinearContainer:new(root,1,0,0)

local lbl = gui.Label:new(root,"Hello!")
local btn1 = gui.Button:new(root,"Button 1")
local btn2 = gui.Button:new(root,"Button 2")
local btn3 = gui.Button:new(root,"Big Btn.")
--local field = gui.TextField:new(root,5,"TextField")
--local area = gui.ListBox:new(root,10,10,{})
--local sb = gui.ScrollBar:new(root,area)

--for i=1,64 do
--    table.insert(area.items,"Item "..tostring(i))
--end
btn1.enabled = false

function btn1:onPressed()
    lbl.text = "Pressed"
    root:onLayout() -- redraw entire screen
end
function btn2:onPressed()
    btn1.enabled = true
    btn1.dirty = true
end

--root:addChild(box2)

--box2:addChild(area,true,true,gui.LinearAlign.START)
--box2:addChild(sb,false,true,gui.LinearAlign.START)
--box2:addChild(box,false,true,gui.LinearAlign.START)

box:addChild(lbl,false,false,gui.LinearAlign.START)
box:addChild(btn1,false,false,gui.LinearAlign.START)
box:addChild(btn2,false,false,gui.LinearAlign.START)
box:addChild(field,false,true,gui.LinearAlign.START)
box:addChild(btn3,true,true,gui.LinearAlign.START)

root:mainLoop()
```

**Comment by lewark** [comment]
Hi, and thanks for trying out this API.

The line that is causing the error is actually this one, because the `field` widget is commented out and therefore nil:

`box:addChild(field,false,true,gui.LinearAlign.START)`

If you comment out this `box:addChild` call as well, then the error goes away. However, the resulting GUI is blank, because the `box` widget is not added to the `root` widget. To fix that problem, you can add a new call to `root:addChild` adding `box` as its child:

`root:addChild(box)`

Hope this helps. The unhelpful error messages in this case were my API's fault, so I might go through and tweak things so that they are more useful. (edit: I added better error messages in the latest commit.)

**Comment by zimavi** [comment]
Thanks! I solve this problem. And thank you for this API. It's very easy to create OS using this. May you please add progress bar?

**Comment by lewark** [comment]
You're welcome! I added `ProgressBar` to the to-do list (#4). It's a widget I've actually been thinking about adding for a while now, so I'll look into it. If you end up making something with this API, let me know; I'd be interested to see it. Also, with the way the API is designed, you can subclass existing widgets if you want to make your own.
